# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

instructors = Instructor.create([{first_name: "Emily", last_name: "Oppenheimer", email: "opemily@gmail.com", password: "password123"}, {first_name: "Bennett", last_name: "James", email: "bennettzjames@gmail.com", password: "password123"}, {first_name: "Dana", last_name: "Czinsky", email: "danamc18@gmail.com", password:"password123"}, {first_name: "Kim", last_name: "Hart", email: "kim_hart@gmail.com", password: "password123"}])
​
cohorts = Cohort.create([{name: "Bacon", instructor_id: 1}, {name: "Lettuce", instructor_id: 1}, {name: "Tomato", instructor_id: 1}, {name:"John", instructor_id: 2}, {name: "Paul", instructor_id: 2}, {name: "George", instructor_id: 2}, {name: "Ringo", instructor_id: 2}], {name: "Leonardo", instructor_id: 3}, {name: "Donatello", instructor_id: 3}, {name: "Raphael", instructor_id: 3}, {name: "Michaelangelo", instructor_id: 3}, {name: "Mr. Brown", instructor_id: 4}, {name: "Mr. Blonde", instructor_id: 4}, {name: "Mr. Pink", instructor_id: 4}, {name: "Mr. White", instructor_id: 4}, {name: "Mr. Blue", instructor_id: 4})
​
students = Student.create([{first_name: "Lucious", last_name: "Lyon", email: "llyon@empire.com", password: "password123", cohort_id: 1}, {first_name: "Cookie", last_name: "Lyon", email: "clyon@empire.com", password: "password123", cohort_id: 1}, {first_name: "Hakeem", last_name: "Lyon", email: "hlyon@empire.com", password: "password123", cohort_id: 1}, {first_name: "Jamal", last_name: "Lyon", email: "jlyon@empire.com", password: "password123", cohort_id: 1}, {first_name: "Walter", last_name: "White", email: "heisenberg@hotmail.com", password: "password123", cohort_id: 2}, {first_name: "Skyler", last_name: "White", email: "skyler@hotmail.com", password: "password123", cohort_id: 2}, {first_name: "Jesse", last_name: "Pinkman", email: "capncook@hotmail.com", password: "password123", cohort_id: 2}, {first_name: "Saul", last_name: "Goodman", email: "sgoodman@bettercallsaul.com", password: "password123", cohort_id: 3}, {first_name: "Hector", last_name: "Salamanca", email: "dingdingding@dingdingding.com", password: "password123", cohort_id: 3}, {first_name: "Tuco", last_name: "Salamanca", email: "tsalamanca@meth.com", password: "password123", cohort_id: 3}, {first_name: "Annie", last_name: "Edison", email: "sgoodman@bettercallsaul.com", password: "password123", cohort_id: 4}, {first_name: "Jeff", last_name: "Winger", email: "jwinger@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Britta", last_name: "Perry", email: "bperry@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Abed", last_name: "Nadir", email: "anadir@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Shirley", last_name: "Bennett", email: "sbennett@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Troy", last_name: "Barnes", email: "tbarnes@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Pierce", last_name: "Hawthorne", email: "phawthorne@greendale.edu", password: "password123", cohort_id: 4}, {first_name: "Bart", last_name: "Simpson", email: "bart@simpson.com", password: "password123", cohort_id: 5}, {first_name: "Lisa", last_name: "Simpson", email: "lisa@simpson.com", password: "password123", cohort_id: 5}, {first_name: "Marge", last_name: "Simpson", email: "marge@simpson.com", password: "password123", cohort_id: 5}, {first_name: "Homer", last_name: "Simpson", email: "bart@simpson.com", password: "password123", cohort_id: 5}, {first_name: "Liz", last_name: "Lemon", email: "llemon@nbc.com", password: "password123", cohort_id: 6}, {first_name: "Tracy", last_name: "Jordan", email: "tjordan@nbc.com", password: "password123", cohort_id: 6}, {first_name: "Jenna", last_name: "Maroney", email: "jmaroney@nbc.com", password: "password123" , cohort_id: 6}, {first_name: "Jenna", last_name: "Donaghy", email: "jmaroney@nbc.com", password: "password123" , cohort_id: 6}, {first_name: "Jenna", last_name: "Donaghy", email: "jmaroney@nbc.com", password: "password123" , cohort_id: 6}])